name: Apply AI PR Suggestions

on:
  issue_comment:
    types: [created]

jobs:
  ai_suggest:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != null

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install PyGithub requests

      - name: Run AI suggestion + create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FASTAPI_URL:   ${{ secrets.FASTAPI_URL }}
        run: python .github/extract_comment.py
